name: "Desplegar pagina"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
  workflow_dispatch:
    # Allow manually running workflow
  # schedule:
    # - cron: "23 2 * * *"

env:
  DEPLOY: >-
    ${{
    github.event_name != 'pull_request'
    &&
    github.ref == 'refs/heads/master'
    }}
  OUTPUT: _html
  TZ: America/Bogota

jobs:
  build:
    name: Construir sitio web lektor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Instalar Lektor
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt

      - name: Construir pagina pybar
        run: lektor build -O '${{ env.OUTPUT }}'

      - name: Desplegar pagina pybaq
        if: env.DEPLOY == 'true'
        run: lektor deploy -O '${{ env.OUTPUT }}' ghpages-https
        env:
          LEKTOR_DEPLOY_USERNAME: pybaq
          LEKTOR_DEPLOY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
